version: '3.7'

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
     - "443:443"
    volumes:
     - wordpress:/var/www/html
     - ./requirements/nginx/ssl:/etc/nginx/ssl
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html 
    restart: always

  db:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: pesilva-
      MYSQL_PASSWORD: /run/secrets/db_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
  
secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt



volumes: 
  wordpress:
  nginx:
  db_data: