version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
     - "443:443" 
    volumes:
     - nginx:/var/www/html
    restart: always

volumes: 
  nginx:
