version: '3.7'

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./requirements/nginx/ssl:/etc/nginx/ssl
    restart: always
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html 
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: /run/secrets/credentials
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - credentials
      - db_password
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: pesilva-
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
  
secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt

volumes: 
  wordpress:
  nginx:
  db_data:
